name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install cmake

    - name: Generate Xcode project with CMake
      run: |
        mkdir build && cd build
        cmake .. -G Xcode \
          -DCMAKE_SYSTEM_NAME=iOS \
          -DCMAKE_OSX_SYSROOT=iphoneos \
          -DCMAKE_OSX_ARCHITECTURES=arm64

    - name: Build the app with xcodebuild
      run: |
        cd build
        xcodebuild -scheme SpaghettiKart -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    - name: Package .ipa
      run: |
        mkdir -p Payload

        if [ -d build/Release-iphoneos/SpaghettiKart.app ]; then
        cp -r build/Release-iphoneos/SpaghettiKart.app Payload/
        elif [ -d build/Release-iphonesimulator/SpaghettiKart.app ]; then
        cp -r build/Release-iphonesimulator/SpaghettiKart.app Payload/
        else
        
        echo "Error: No built app found."
        exit 1
        fi

    - name: Rename IPA file
      run: mv Package.ipa Spaghetti.ipa
    - name: Upload .ipa artifact
      uses: actions/upload-artifact@v4

      with:
        name: SpaghettiKart-ipa
        path: SpaghettiKart.ipa
